# Generated by Django 5.0.2 on 2024-05-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_referral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referral',
            new_name='StatsData',
        ),
    ]
