# Generated by Django 5.0.2 on 2024-05-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_referrallink_referal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrallink',
            old_name='referal',
            new_name='text',
        ),
    ]
