# Generated by Django 5.0.6 on 2024-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_referal_referrallink_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrallink',
            options={'verbose_name': 'Реферальная ссылка', 'verbose_name_plural': 'Реферальные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='statsdata',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Посещения'),
        ),
        migrations.AlterField(
            model_name='statsdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='statsdata',
            name='ip_address',
            field=models.CharField(max_length=60, verbose_name='Айпи адрес'),
        ),
        migrations.AlterField(
            model_name='statsdata',
            name='social_network',
            field=models.CharField(max_length=20, verbose_name='Социальная сеть'),
        ),
    ]
